on:
  workflow_dispatch:
name: 'My workflow'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/javascript-action@main
        id: 'js-action'
        with: 
          milliseconds: 100

      - run: |
          echo "Output from the action: $TIME"
        env: 
          TIME: ${{ steps.js-action.outputs.time }}

      - uses: actions/container-action@main
        id: 'container-action'
        with: 
          who-to-greet: "Jesse"

      - run: |
          echo "Output from the container action: $GREETING"
        env:
          GREETING: ${{ steps.container-action.greeting }}


